### ISSUE TITLE
Python example/balance.py does not 'compile'

### ISSUE THREAD

**Issue by rickvanderzwet** [messagebird/python-rest-api#4]
Running API via python does not work:
```
[rvdzwet@rvdzwet-asus python-rest-api]$ python examples/balance.py

An error occured while requesting a Balance object:

  code        : 2
  description : Request not allowed (incorrect access_key)
  parameter   : access_key
```

Fixed curl request (with same dummy key) goes just fine:
```
[rvdzwet@rvdzwet-asus ~]$ curl  https://rest.messagebird.com/balance -H 'Authorization: AccessKey test_gshuPaZoeEG6ovbc8M79w0QyM'
{"payment":"prepaid","type":"credits","amount":10.1}
```

**Comment by samwierema** [comment]
Thanks for opening an issue @rickvanderzwet. 

I've not been able to reproduce this yet. Just to be sure, could you let me know which version of Python you're running?

**Comment by rickvanderzwet** [comment]
```
[rvdzwet@rvdzwet-asus ~]$ python -V
Python 2.7.8

[rvdzwet@rvdzwet-asus tmp]$ git clone https://github.com/messagebird/python-rest-api.git
Cloning into 'python-rest-api'...
remote: Counting objects: 66, done.
remote: Total 66 (delta 0), reused 0 (delta 0), pack-reused 66
Unpacking objects: 100% (66/66), done.
Checking connectivity... done.
[rvdzwet@rvdzwet-asus tmp]$ cd python-rest-api/
 
[rvdzwet@rvdzwet-asus python-rest-api]$ python examples/balance.py 

An error occured while requesting a Balance object:

  code        : 2
  description : Request not allowed (incorrect access_key)
  parameter   : access_key

[rvdzwet@rvdzwet-asus python-rest-api]$ 
```

**Comment by prep** [comment]
Hey @rickvanderzwet,

Like @samwierema I cannot reproduce it either:

```
$ git clone https://github.com/messagebird/python-rest-api
Cloning into 'python-rest-api'...
remote: Counting objects: 66, done.
remote: Total 66 (delta 0), reused 0 (delta 0), pack-reused 66
Unpacking objects: 100% (66/66), done.
Checking connectivity... done.

$ cd python-rest-api/

$ python -V
Python 2.7.10

$ python examples/balance.py 

The following information was returned as a Balance object:

  amount  : 10
  type    : credits
  payment : prepaid
```

Could you generate your own key on the messagebird.com website, replace it with the example key and see what happens then?

**Comment by rickvanderzwet** [comment]
Tried at alternative server which is running python version (2.7.10) instead, this works fine. Maybe the combination of Python 2.7.8 and python-requests module 2.7.0 is causing the issue?
```
rvdzwet@pzwet:/home/rvdzwet/src % git clone https://github.com/messagebird/python-rest-api
Cloning into 'python-rest-api'...
remote: Counting objects: 66, done.
remote: Total 66 (delta 0), reused 0 (delta 0), pack-reused 66
Unpacking objects: 100% (66/66), done.
Checking connectivity... done.

rvdzwet@pzwet:/home/rvdzwet/src % cd python-rest-api/

rvdzwet@pzwet:/home/rvdzwet/src/python-rest-api % sudo pkg install py27-requests
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
Updating database digests format: 100%
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	py27-requests: 2.7.0

The process will require 3 MiB more space.
466 KiB to be downloaded.

Proceed with this action? [y/N]: y
[pzwet.vanderzwet.net] Fetching py27-requests-2.7.0.txz: 100%  466 KiB 477.3kB/s    00:01    
Checking integrity... done (0 conflicting)
[pzwet.vanderzwet.net] [1/1] Installing py27-requests-2.7.0...
[pzwet.vanderzwet.net] [1/1] Extracting py27-requests-2.7.0: 100%


rvdzwet@pzwet:/home/rvdzwet/src/python-rest-api % python examples/balance.py

The following information was returned as a Balance object:

  amount  : 10
  type    : credits
  payment : prepaid

rvdzwet@pzwet:/home/rvdzwet/src/python-rest-api % python -V
Python 2.7.10
```

**Comment by rickvanderzwet** [comment]
Using the request module straight from source: 
```
[rvdzwet@rvdzwet-asus python-rest-api]$ git clone git://github.com/kennethreitz/requests.git

[rvdzwet@rvdzwet-asus python-rest-api]$ PYTHONPATH=./requests python examples/balance.py 

An error occured while requesting a Balance object:

  code        : 2
  description : Request not allowed (incorrect access_key)
  parameter   : access_key

[rvdzwet@rvdzwet-asus python-rest-api]$ PYTHONPATH=./requests python3 examples/balance.py 

An error occured while requesting a Balance object:

  code        : 2
  description : Request not allowed (incorrect access_key)
  parameter   : access_key


[rvdzwet@rvdzwet-asus python-rest-api]$ cd requests/


[rvdzwet@rvdzwet-asus requests]$ ./test_requests.py 
................FF.................................................................................................................................
======================================================================
FAIL: test_auth_is_retained_for_redirect_on_host (__main__.RequestsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_requests.py", line 1002, in test_auth_is_retained_for_redirect_on_host
    assert h1 == h2
AssertionError

======================================================================
FAIL: test_auth_is_stripped_on_redirect_off_host (__main__.RequestsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_requests.py", line 995, in test_auth_is_stripped_on_redirect_off_host
    assert not r.request.headers.get('Authorization', '')
AssertionError

----------------------------------------------------------------------
Ran 147 tests in 32.913s

FAILED (failures=2)
```

So the request module on this specific host is causing the issues. The 'why?' is still unclear to me.

**Comment by rickvanderzwet** [comment]
Found the culprit, which turned to be a human error, specifying incorrect entries in `~/.netrc`.  Details at https://github.com/kennethreitz/requests/issues/2787

**Comment by samwierema** [comment]
@rickvanderzwet fijn om te horen dat het is opgelost!
