### ISSUE TITLE
AttributeError: partially initialized module 'messagebird' has no attribute 'Client' (most likely due to a circular import)

### ISSUE THREAD

**Issue by wilfredinni** [messagebird/python-rest-api#55]
After pip install, import and initializing the client

```
Traceback (most recent call last):
  File "messagebird.py", line 1, in <module>
    import messagebird
  File "/home/carlos/Escritorio/projects/twilio/messagebird.py", line 2, in <module>
    client = messagebird.Client('YOUR_ACCESS_KEY')
AttributeError: partially initialized module 'messagebird' has no attribute 'Client' (most likely due to a circular import)
```

Thank you

**Comment by wilfredinni** [comment]
my mistake
